[package]
name = "abpoa"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "abpoa_check"
path = "src/main/rust/main.rs"

[lib]
name = "abpoa"
path = "src/main/rust/lib.rs"

[build-dependencies]
bindgen = "0.64"

[dependencies]
env_logger = "0.9"
libc = "0.2"
log = "0.4"
thiserror = "1.0"

